sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: zzy1998

  redis:
    host: 127.0.0.1
    port: 6379
    database: 10
  wechat:
    appid: wxaf687541ed43f633
    secret: 2d74613a02b71a0c2cc3593c5aa70db6